<a href="https://colab.research.google.com/github/kushvikas/Deep_Learning/blob/master/NNpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch.jit import script, trace
import torch.nn as nn
# Initialize the scores and ground truth
logits = torch.tensor([[-1.2,0.12,4.8]])
ground_truth = torch.tensor([2])

# Instantiate cross entropy loss
criterion = nn.CrossEntropyLoss()
print(criterion)
# Compute and print the loss
loss = criterion(logits, ground_truth)
print(loss)

CrossEntropyLoss()
tensor(0.0117)


In [ ]:
# Initialize the scores and ground truth
logits = torch.rand(1,1000)
ground_truth = torch.tensor([111])
print(logits.shape)

criterion = nn.CrossEntropyLoss()

loss = criterion(logits, ground_truth)
print(loss)

torch.Size([1, 1000])
tensor(7.0347)


In [ ]:
import torchvision
import torch.utils.data
import torchvision.transforms as transforms

# Transform the data to torch tensors and normalize it 
# Transform the data to torch tensors and normalize it 
transform = transforms.Compose([transforms.ToTensor(),
								transforms.Normalize((0.1307), ((0.3081)))])

# Prepare training set and testing set
trainset = torchvision.datasets.MNIST(root='./data', train=True, 
									  download=True, transform=transform)
testset = torchvision.datasets.MNIST(root='./data', train=False,
			   download=True, transform=transform)

# Prepare training loader and testing loader
trainloader = torch.utils.data.DataLoader(trainset, batch_size=32,
                                          shuffle=True, num_workers=0)
testloader = torch.utils.data.DataLoader(testset,  batch_size=32,
										 shuffle=True, num_workers=0) 

  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw



TypeError: ignored

In [ ]:
# Define the class Net
class Net(nn.Module):
    def __init__(self):    
    	# Define all the parameters of the net
        super(Net, self).__init__()
        self.fc1 = nn.Linear(28 * 28 * 1, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):    
    	# Do the forward pass
        x = nn.functional.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [ ]:
#### Training Instantiate the Adam optimizer and Cross-Entropy loss function
model = Net()
optimizer = torch.optim.Adam(model.parameters(),lr = 3e-4)
criterion = nn.CrossEntropyLoss() # as it is classification problem use cross entropy

for batch_idx,data_target in enumerate(trainloader):
  data = data_target[0]
  target = data_target[1]
  data = data.view(-1, 28 * 28)
  optimizer.zero_grad()

  # Complete a forward pass
  output = model(data)
  #print(output)

  # Compute the loss, gradients and change the weights
  loss = criterion(output, target)
  loss.backward()
  optimizer.step() # change the weights
  #print(loss)
  #print(optimizer.step())

In [ ]:
##### Make prediction
# Set the model in eval mode
correct, total = 0,0
predictions = []
model.eval()

for i, data in enumerate(testloader, 0):
    inputs, labels = data
    
    # Put each image into a vector
    inputs = inputs.view(-1, 28 * 28)
    
    # Do the forward pass and get the predictions
    outputs = model(inputs)
    _, predicted = torch.max(outputs.data, 1)
    predictions.append(outputs)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
print('The testing set accuracy of the network is: %d %%' % (100 * correct / total))




The testing set accuracy of the network is: 95 %


In [ ]:
# CNN
# Convolution operator - OOP way
import torch
import torch.nn

# Create 10 random images of shape (1, 28, 28)
images = torch.rand(10, 1, 28, 28)

# Build 6 conv. filters
conv_filters = torch.nn.Conv2d(in_channels=1, out_channels=6, kernel_size=3, stride=1, padding=1)

# Convolve the image with the filters
output_feature = conv_filters(images)
print(output_feature.shape)


torch.Size([10, 6, 28, 28])


In [ ]:
# CNN
# Convolution operator - Functional way
import torch
import torch.nn.functional

# Create 10 random images
image = torch.rand(10, 1, 28, 28)


# Create 6 filters
filters = torch.rand(6, 1, 3, 3)

# Convolve the image with the filters
output_feature = torch.nn.functional.conv2d(image, filters, stride=1, padding=1)
print(output_feature.shape)



torch.Size([10, 6, 28, 28])


In [ ]:
# CNNs is the pooling operator, which can come in two different ways. The convolutions are used to extract features from the image, 
# while the ***pooling*** is a way of feature selection, choosing the most dominant features from the image, 
# or combining different features. Additionally, they lower the resolution of the images, making the computations more efficient.

##### Pooling ** Max pool
import torch
import torch.nn
import torch.nn.functional

# Image
im = torch.Tensor([[[[3,1,3,5],[6,0,7,9],[3,2,1,4],[0,2,4,3]]]])
# Build a pooling operator with size `2`.
max_pooling = torch.nn.MaxPool2d(2)

# Apply the pooling operator  *** object oriented way
output_feature = max_pooling(im)

# Use pooling operator in the image ***function way
output_feature_F = torch.nn.functional.max_pool2d(im, 2)

# print the results of both cases
print(output_feature)
print(output_feature_F)



tensor([[[[6., 9.],
          [3., 4.]]]])
tensor([[[[6., 9.],
          [3., 4.]]]])


In [ ]:
##### Pooling ** Average pool
# Image
import torch
import torch.nn
import torch.nn.functional

im = torch.Tensor([[[[3,1,3,5],[6,0,7,9],[3,2,1,4],[0,2,4,3]]]])

# Build a pooling operator with size `2`.
avg_pooling =  torch.nn.AvgPool2d(2)


# Apply the pooling operator  *** object oriented way
output_feature = avg_pooling(im)

# Use pooling operator in the image ***function way
output_feature_F = torch.nn.functional.avg_pool2d(im,2)

# print the results of both cases
print(output_feature)
print(output_feature_F)


tensor([[[[2.5000, 6.0000],
          [1.7500, 3.0000]]]])
tensor([[[[2.5000, 6.0000],
          [1.7500, 3.0000]]]])


In [ ]:
#  first CNN - __init__ method

import torch
import torch.nn as nn

class CNN(nn.Module):
    def __init__(self, num_classes = 10):
        super(CNN, self).__init__()
		
        # Instantiate the ReLU nonlinearity
        self.relu = nn.ReLU()
        
        # Instantiate two convolutional layers
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1)
        
        # Instantiate a max pooling layer
        self.pool = nn.MaxPool2d(2, 2)
        
        # Instantiate a fully connected layer
        self.fc = nn.Linear(10 * 7 * 7, num_classes)

    def forward(self, x):
  
        # Apply conv followd by relu, then in next line pool
        x = self.relu(self.conv1(x))
        x = self.pool(x)

        # Apply conv followd by relu, then in next line pool
        x = self.relu(self.conv2(x))
        x = self.pool(x)

        # Prepare the image for the fully connected layer
        x = x.view(-1,10 * 7 * 7)

        # Apply the fully connected layer and return the result
        return self.fc(x)      
                                                                                                                                                                                                                                                                             

In [ ]:
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
#training CNN
cnn = CNN()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(cnn.parameters(), lr = 3e-04)

for i, data in enumerate(trainloader, 0):
    inputs, labels = data
    optimizer.zero_grad()

    # Compute the forward pass
    outputs = cnn(inputs)
        
    # Compute the loss function
    loss = criterion(outputs, labels)
        
    # Compute the gradients
    loss.backward()
        
    # Update the weights
    optimizer.step()

print('Finished Training')

Finished Training


In [ ]:
# Using CNNs to make predictions

##### Make prediction
# Set the model in eval mode
predictions = []

# Iterate over the data in the test_loader
for i, data in enumerate(testloader):

    # Get the image and label from data
    image, label = data

    # Make a forward pass in the net with your image
    output = cnn(image)

    # Argmax the results of the net
    _, predicted = torch.max(output.data, 1)
    print(predicted.shape)
    print(label.shape)
    
    print(predicted == label)

    if predicted == label:
      print(str(predicted))
    else:
      print(str(label))
    



torch.Size([32])
torch.Size([32])
tensor([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True])


RuntimeError: ignored

In [83]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        
        # Declare all the layers for feature extraction
        self.features = nn.Sequential(nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1), 
                                      nn.ReLU(inplace=True),
                                      nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1), 
                                      nn.MaxPool2d(2, 2), nn.ReLU(inplace=True),
                                      nn.Conv2d(in_channels=10, out_channels=20, kernel_size=3, padding=1),
                                      nn.ReLU(inplace=True),
                                      nn.Conv2d(in_channels=20, out_channels=40, kernel_size=3, padding=1),
                                      nn.MaxPool2d(2, 2), nn.ReLU(inplace=True))
        
        # Declare all the layers for classification
        self.classifier = nn.Sequential(nn.Linear(7 * 7 * 40, 1024), nn.ReLU(inplace=True),
                                       	nn.Linear(1024, 2048), nn.ReLU(inplace=True),
                                        nn.Linear(2048, 10))
        
    def forward(self, x):
      
        # Apply the feature extractor in the input
        x = self.features(x)
        
        # Squeeze the three spatial dimensions in one
        x = x.view(-1, 7 * 7 * 40) # 40 because its the last in the channel 
        
        # Classify the images
        x = self.classifier(x)
        return x
        